remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hypericat's Portofolio
description: A highlight from my past projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect